import XCTest
// BetterEnv is generated by the plugin, no import needed

final class BetterEnvTests: XCTestCase {
    func testGetExistingRuntimeEnv() {
        // PATH should always exist in runtime environment
        let path = BetterEnv.get("PATH")
        XCTAssertNotNil(path)
    }

    func testHasExistingRuntimeEnv() {
        XCTAssertTrue(BetterEnv.has("PATH"))
    }

    func testGetNonExistentEnv() {
        let value = BetterEnv.get("BETTERENV_NONEXISTENT_KEY_12345")
        XCTAssertNil(value)
    }

    func testHasNonExistentEnv() {
        XCTAssertFalse(BetterEnv.has("BETTERENV_NONEXISTENT_KEY_12345"))
    }

    func testAllContainsRuntimeEnv() {
        let all = BetterEnv.all
        XCTAssertNotNil(all["PATH"])
    }

    func testSubscriptWithRuntimeEnv() {
        // This should not fatal error since PATH exists
        let path = BetterEnv["PATH"]
        XCTAssertFalse(path.isEmpty)
    }

    // Tests for compile-time environment variables from .env file
    func testCompiledEnvApiKey() {
        // This tests that the .env file was read at compile time
        let apiKey = BetterEnv["API_KEY"]
        XCTAssertEqual(apiKey, "test_key_12345")
    }

    func testCompiledEnvDebug() {
        let debug = BetterEnv["DEBUG"]
        XCTAssertEqual(debug, "true")
    }

    func testCompiledEnvAppName() {
        let appName = BetterEnv.get("APP_NAME")
        XCTAssertEqual(appName, "BetterEnvDemo")
    }

    func testCompiledDictionary() {
        let compiled = BetterEnv.compiledEnvironment
        XCTAssertEqual(compiled["API_KEY"], "test_key_12345")
        XCTAssertEqual(compiled["DEBUG"], "true")
        XCTAssertEqual(compiled["APP_NAME"], "BetterEnvDemo")
        XCTAssertEqual(compiled["DATABASE_URL"], "postgres://localhost:5432/testdb")
    }
}
