import XCTest
// BetterEnv is generated by the plugin, no import needed

final class BetterEnvTests: XCTestCase {
    
    // MARK: - Runtime Tests
    
    func testRuntimeGetExisting() {
        // PATH should always exist in runtime environment
        let path = BetterEnv.runtime.get("PATH")
        XCTAssertNotNil(path)
    }

    func testRuntimeHasExisting() {
        XCTAssertTrue(BetterEnv.runtime.has("PATH"))
    }

    func testRuntimeGetNonExistent() {
        let value = BetterEnv.runtime.get("BETTERENV_NONEXISTENT_KEY_12345")
        XCTAssertNil(value)
    }

    func testRuntimeHasNonExistent() {
        XCTAssertFalse(BetterEnv.runtime.has("BETTERENV_NONEXISTENT_KEY_12345"))
    }

    func testRuntimeGetAll() {
        let all = BetterEnv.runtime.getAll()
        XCTAssertNotNil(all["PATH"])
    }

    // MARK: - Compile Tests

    func testCompileGetApiKey() {
        // This tests that the .env file was read at compile time
        let apiKey = BetterEnv.compile.get("API_KEY")
        XCTAssertEqual(apiKey, "test_key_12345")
    }

    func testCompileGetDebug() {
        let debug = BetterEnv.compile.get("DEBUG")
        XCTAssertEqual(debug, "true")
    }

    func testCompileGetAppName() {
        let appName = BetterEnv.compile.get("APP_NAME")
        XCTAssertEqual(appName, "BetterEnvDemo")
    }

    func testCompileHas() {
        XCTAssertTrue(BetterEnv.compile.has("API_KEY"))
        XCTAssertFalse(BetterEnv.compile.has("NONEXISTENT"))
    }

    func testCompileGetAll() {
        let compiled = BetterEnv.compile.getAll()
        XCTAssertEqual(compiled["API_KEY"], "test_key_12345")
        XCTAssertEqual(compiled["DEBUG"], "true")
        XCTAssertEqual(compiled["APP_NAME"], "BetterEnvDemo")
        XCTAssertEqual(compiled["DATABASE_URL"], "postgres://localhost:5432/testdb")
    }
    
    // MARK: - Combined Access Tests
    
    func testCombinedGet() async throws {
        // Should find compile-time value
        let apiKey = try await BetterEnv.get("API_KEY")
        XCTAssertEqual(apiKey, "test_key_12345")
        
        // Should find runtime value
        let path = try await BetterEnv.get("PATH")
        XCTAssertNotNil(path)
        
        // Should return nil for nonexistent
        let nonexistent = try await BetterEnv.get("BETTERENV_NONEXISTENT_KEY_12345")
        XCTAssertNil(nonexistent)
    }
    
    func testCombinedGetAll() async throws {
        let all = try await BetterEnv.getAll()
        // Should contain compile-time values
        XCTAssertEqual(all["API_KEY"], "test_key_12345")
        // Should contain runtime values
        XCTAssertNotNil(all["PATH"])
    }
    
    func testCombinedHas() async throws {
        let hasApiKey = try await BetterEnv.has("API_KEY")
        XCTAssertTrue(hasApiKey)
        
        let hasPath = try await BetterEnv.has("PATH")
        XCTAssertTrue(hasPath)
        
        let hasNonexistent = try await BetterEnv.has("BETTERENV_NONEXISTENT_KEY_12345")
        XCTAssertFalse(hasNonexistent)
    }
}
